### ISSUE TITLE
Make each test independent

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rust#109] opened 2021-02-15 09:50 UTC
To avoid side effects between each test, the tests should all be independent.

It means, at the beginning of each test:
- create the needed index(es)
- push documents according to the test
- update settings if necessary

And at the end of each test:
- remove the index(es)

This is linked to #29

**Comment by sanders41** [comment] 2021-02-19 19:23
I have looked into creating and deleting the index with each test and the problem I have run into is because the tests are running in threads, the tests still fail. The reason for this is multiple tests can be running at the same time trying to use the same index name. One solution to this is to run the tests all in a single thread with `cargo test -- --test-threads=1`. By doing this the tests no longer overlap and will pass, but the test take MUCH longer to run.

**Comment by Mubelotix** [comment] 2021-02-20 09:24
@sanders41 I have already thought about this issue. Your third solution has already been applied [here](https://github.com/meilisearch/meilisearch-rust/blob/a78ec535dab6e3fdbb34a9d72900aef25fa289dc/src/search.rs#L284) and I plan to extend this structure to all other tests. However, there is another issue that you did not expect. For a reason I am unable to explain when tests make simultaneous requests to the MeiliSearch server, requests will hang and never get answers. So we cannot remove `test-threads=1` anyway.

**Comment by sanders41** [comment] 2021-02-20 11:45
> For a reason I am unable to explain when tests make simultaneous requests to the MeiliSearch server, requests will hang and never get answers.

I have seen this issue also. I was guessing it was happening because of the index overlap, but sounds like your testing shows that isn’t the cause.

**Comment by irevoire** [comment] 2022-02-09 00:06
Closed by #225

**Closed by irevoire** 2022-02-09 00:06 UTC
Labels: good first issue
